// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC39gItfLCReNCqg9UNzqCCg_wxVO0LuQs',
    appId: '1:469932598682:android:e55fe0debeeeb368bb8623',
    messagingSenderId: '469932598682',
    projectId: 'pull-68ba0',
    storageBucket: 'pull-68ba0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZTpiH1tZK5r4ssGdMiwZQ-XstKgE4rDI',
    appId: '1:469932598682:ios:996247193c6d1f2abb8623',
    messagingSenderId: '469932598682',
    projectId: 'pull-68ba0',
    storageBucket: 'pull-68ba0.appspot.com',
    androidClientId: '469932598682-3gp5n99khmj8qe9pjmduc8v7aarj0tgh.apps.googleusercontent.com',
    iosClientId: '469932598682-kujqamq7124c1fiejp14vm38t9jpc4v7.apps.googleusercontent.com',
    iosBundleId: 'pull.dating.pull',
  );
}
