import 'dart:io';

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:pull/models/message.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'chat.freezed.dart';
// optional: Since our chat class is serializable, we must add this line.
// But if Chat was not serializable, we could skip it.
// part 'chat.g.dart';

@freezed
class Chat with _$Chat {
  factory Chat({

    //don't need to store the uuids since they are in either the person class under match,
    //or in the uuid provider for the user using the app.

    ///the room id, used for database access. (constructed from the uuid pair)
    required String roomid,
    ///the list of messages in that chat thus far.
    required List<PullMessage> messages,
  }) = _Chat;

  //factory Chat.fromJson(Map<String, Object?> json) => _$ChatFromJson(json);
}