import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'filter.freezed.dart';
// optional: Since our profile class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'filter.g.dart';

@unfreezed
class Filter with _$Filter {
  factory Filter({
    required bool men,
    required bool women,
    required bool nonBinary,
    required int minAge,
    required int maxAge,
    required int minHeight,
    required int maxHeight,
    required bool obese,
    required bool heavy,
    required bool muscular,
    required bool average,
    required bool lean,
    ///max distance to the other user in meters
    required int maxDistance,
  }) = _Filter;

factory Filter.fromJson(Map<String, Object?> json)
=> _$FilterFromJson(json);
}