import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'profile.freezed.dart';
// optional: Since our profile class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
//part 'profile.g.dart';

@unfreezed
class Profile with _$Profile {
  factory Profile({
    //the unique identifier of the user, used for backend api calls
    required String uuid,
    required String name,
    required DateTime birthdate,
    String? bodyType,
    required String gender,
    double? height,
    required String datingGoal,
    String? biography,
    required double latitude,
    required double longitude,
    //for images
    required List<Image?> images, //this might have to be changed to File instead of Image

  }) = _Profile;

  //factory Profile.fromJson(Map<String, Object?> json)
  //=> _$ProfileFromJson(json);
}