//this class combines two others, the chat and person to give all the information needed about a user

import 'dart:io';

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:pull/models/chat.dart';
import 'package:pull/models/person.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'pullmatch.freezed.dart';
// optional: Since our match class is serializable, we must add this line.
// But if PullMatch was not serializable, we could skip it.
//part 'pullmatch.g.dart';

@unfreezed
class PullMatch with _$PullMatch {
  factory PullMatch({
    //the unique identifier of the user, used for backend api calls
    required Person person,
    required Chat chat,
  }) = _PullMatch;

//factory PullMatch.fromJson(Map<String, Object?> json)
//=> _$PullMatchFromJson(json);
}